
skillMetadata:
  sections:
    - name: Last reading session
      fields:
        - name: last_date
          type: text
          label: Last date
          value:
        - name: last_prog_count
          type: number
          label: Last programme
          value: 0
        - name: last_book_count
          type: number
          label: Last book
          value: 0
        - name: last_chapter_count
          type: number
          label: Last chapter
          value: 0
